name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: guardian/actions-assume-aws-role@v1.0.0
        with:
          awsRoleToAssume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
      - uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: yarn
          cache-dependency-path: |
            cdk/yarn.lock
            lambda/yarn.lock
      - run: ./scripts/ci.sh
